sudo: false

os:
  - linux
  - osx
  
language: node_js

node_js:
- '8'

cache:
  directories:
  - node_modules

before_install:
  - npm install -g npm@latest
  - npm install --dev
  - npm install
  - npm install -g eslint electron electron-packager

script:
  - eslint .
  - npm run react-test
  - npm run react-build
  - npm run build
  - npm start &
